name: Publish GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert 20210716-reading-trpl-public
        uses: docker://pandoc/core:2.12
        with:
          args: >-
            -f markdown+emoji 20210716-reading-trpl-public/index.md
	          -t revealjs -o 20210716-reading-trpl-public/index.html
	          --template=20210716-reading-trpl-public/template.html
	          -s -c 20210716-reading-trpl-public/custom.css
	          --slide-level=2

      - name: Convert 20210820-reading-trpl-public
        uses: docker://pandoc/core:2.12
        with:
          args: >-
            -f markdown+emoji 20210820-reading-trpl-public/index.md
	          -t revealjs -o 20210820-reading-trpl-public/index.html
	          --template=20210820-reading-trpl-public/template.html
	          -s -c 20210820-reading-trpl-public/custom.css
	          --slide-level=2
      
      - name: Convert 20211001-reading-trpl-public
        uses: KoharaKazuya/marp-cli-action@v1
        with:
          config-file: ./20211001-reading-trpl-public/.marprc.yml
          generate-pdf: false
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./
