name: Publish GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert Markdown into HTML with reveal.js
        run: apt install pandoc -y; for d in 20210716-reading-trpl-public 20210820-reading-trpl-public; do make -C $f; done
      
      - name: Convert Markdown into HTML with Marp
        uses: KoharaKazuya/marp-cli-action@v1
        with:
          config-file: ./20211001-reading-trpl-public/.marprc.yml
          generate-pdf: false
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./
